export const keywords = {
    personajes: [
        "mago", "guerrero", "pícaro", "tabernero", "rey", "mercenario",
        "hechicero", "bardo", "paladín", "gnomo", "elfo", "orco",
        "goblin", "dragón", "caballero", "bruja", "enano", "héroe",
        "ogro", "hadas", "duende", "troll", "vampiro", "esqueleto"
    ],
    acciones: [
        "pelea", "pulso", "discusión", "duelo", "banquete", "robo",
        "hechizo", "maldición", "fuga", "bebida", "apuesta", "exploración",
        "entrenamiento", "caza", "búsqueda de tesoro", "rescate",
        "emboscada", "travesía por el bosque", "negociación con un rey",
        "investigación de un misterio", "viaje por un portal mágico",
        "reparación de un objeto encantado", "prueba de valor",
        "entrega de mensaje secreto", "defensa de la taberna",
        "intento de hechizo fallido", "competencia de fuerza",
        "carrera con caballos", "esquivar una trampa", "baile improvisado",
        "lanzamiento de pasteles", "cantar en público", "imitar al dragón"
    ],
    emociones: [
        "enamorado", "enfadado", "asustado", "confundido", "borracho",
        "eufórico", "nervioso", "sorprendido", "desconcertado", "desafiante",
        "celoso", "aliviado", "impaciente", "perezoso", "atrevido", "inseguro",
        "preocupado", "tímido", "orgulloso", "curioso", "travieso", "despistado",
        "ansioso", "dramático", "exagerado", "torpe", "histérico", "hiperactivo"
    ],
    lugares: [
        "taberna", "castillo", "bosque encantado", "mazmorra", "torre de mago",
        "caverna secreta", "puente colgante", "pozo sin fondo", "foso con barro", "gruta misteriosa",
        "ruinas antiguas", "templo abandonado", "catedral de cristal", "aldea olvidada", "mercado bullicioso",
        "camino del comerciante", "lago encantado", "isla misteriosa", "ciudadela fortificada", "campo de batalla",
        "carretera polvorienta", "puerta secreta", "torre derruida", "laboratorio alquímico", "biblioteca arcana",
        "jardín prohibido", "cueva de dragones", "fortaleza de orcos", "aldea de gnomos", "palacio real",
        "puerto pirata", "refugio de bandidos", "camino de montaña", "puerto fantasmal", "ruinas de un coloso",
        "minas abandonadas", "bosque de hongos gigantes", "templo subterráneo", "torre de vigilancia", "laberinto de setos",
        "puerta dimensional", "camino de caravanas", "plaza del pueblo", "mercado nocturno", "arena de gladiadores",
        "cueva de cristal", "gruta subterránea", "cabaña del ermitaño", "camino del héroe", "puente de cuerda",
        "pradera mágica", "torre del hechicero loco", "templo de los elementos", "bosque de niebla", "valle de los ecos",
        "caverna de los susurros", "castillo en ruinas", "puerto de mercaderes", "cueva de los trolls", "puente sobre lava",
        "lago de los espíritus", "torre del reloj encantado", "oceano", "desierto", "palacio",
        "montaña nevada", "pantano tenebroso", "jungla misteriosa", "río caudaloso", "ciudad abandonada",
        "villa costera", "isla volcánica", "camino nevado", "fortaleza en la cima", "túnel subterráneo",
        "caverna helada", "cueva luminosa", "gruta de cristales", "puente roto", "campo de flores mágicas",
        "bosque de sombras", "torre flotante", "templo del fuego", "lago congelado", "mina de gemas",
        "puerto antiguo", "callejón oscuro", "catedral en ruinas", "plaza central", "castillo flotante"
    ],
    consecuencias: [
        "terminó tropezando en el momento más crítico",
        "decidió lanzar un hechizo al azar",
        "no recuerda por qué estaba haciendo eso",
        "todos se rieron de la situación",
        "terminó enredado en su propia trampa",
        "finalmente decidió huir",
        "casi destruye todo a su alrededor",
        "se olvidó por completo de su misión",
        "se quedó dormido en medio de la pelea",
        "el dragón lo confundió con un árbol",
        "descubrió que la poción era solo jugo",
        "el tabernero se durmió de aburrimiento",
        "accidentalmente lanzó confeti mágico",
        "un gnomo travieso le gastó una broma",
        "la espada se quedó atascada en el techo",
        "un hechizo salió volando hacia la pared",
        "la criatura empezó a bailar en lugar de atacar",
        "se convirtió en una rana por error",
        "los compañeros no pudieron contener la risa",
        "todos terminaron bailando en la taberna",
        "el tesoro se escondió solo",
        "el mapa se quemó sin querer",
        "su sombrero salió volando y aterrizó en la cabeza del dragón",
        "un pastel mágico explotó sobre su cara",
        "la varita se volvió loca y comenzó a perseguirlo",
        "el perro del tabernero lo confundió con un gnomo",
        "la mesa del banquete salió rodando colina abajo"
    ]
};

export const phrases = {
    personajes: [
        "ha decidido tomarse un descanso antes de actuar",
        "se distrajo con algo brillante",
        "se olvidó por completo de su misión",
        "está demasiado concentrado en sus hechizos",
        "suspira profundamente antes de moverse",
        "mira alrededor sin saber qué hacer",
        "intentó impresionar a todos con sus habilidades",
        "se quedó atrapado en su propia capa",
        "habló con su reflejo en el espejo",
        "se puso a bailar sin motivo aparente"
    ],
    acciones: [
        "terminó tropezando en el momento más crítico",
        "decidió lanzar un hechizo al azar",
        "no recuerda por qué estaba haciendo eso",
        "intentó algo que nadie esperaba",
        "provocó un caos sin querer",
        "su plan salió completamente al revés",
        "acaba de inventar un nuevo movimiento de lucha",
        "empezó a cantar mientras peleaba",
        "confundió su varita con un tenedor",
        "intentó abrir la puerta con magia… y explotó algo"
    ],
    emociones: [
        "pero estaba demasiado nervioso para reaccionar",
        "su corazón latía con fuerza y se bloqueó",
        "la emoción lo hizo actuar de forma inesperada",
        "no podía controlar la risa",
        "se sintió desconcertado y confundido",
        "su orgullo le impidió retroceder",
        "estaba tan emocionado que olvidó respirar",
        "se quedó boquiabierto mirando al dragón",
        "sus manos temblaban como gelatina",
        "intentaba mantener la calma pero fallaba estrepitosamente"
    ],
    objetos_lugares: [
        "y rompió algo importante",
        "y encontró algo sorprendente",
        "y casi destruye todo a su alrededor",
        "y se quedó atrapado por un objeto mágico",
        "y provocó un efecto inesperado en el lugar",
        "y causó que todos se dispersaran",
        "y terminó cubierto de barro",
        "y activó una trampa secreta por accidente",
        "y un cofre explotó con confeti",
        "y una escalera cayó sobre su cabeza"
    ],
    consecuencias: [
        "finalmente decidió huir",
        "terminó enredado en su propia trampa",
        "todos se rieron de la situación",
        "casi destruye todo a su alrededor",
        "se quedó dormido en medio de la pelea",
        "el dragón lo confundió con un árbol",
        "descubrió que la poción era solo jugo",
        "accidentalmente lanzó confeti mágico",
        "un gnomo travieso le gastó una broma",
        "la espada se quedó atascada en el techo",
        "la criatura empezó a bailar en lugar de atacar",
        "se convirtió en una rana por error",
        "los compañeros no pudieron contener la risa",
        "todos terminaron bailando en la taberna",
        "el tesoro se escondió solo",
        "el mapa se quemó sin querer",
        "su sombrero salió volando y aterrizó en la cabeza del dragón",
        "un pastel mágico explotó sobre su cara",
        "la varita se volvió loca y comenzó a perseguirlo",
        "el perro del tabernero lo confundió con un gnomo",
        "la mesa del banquete salió rodando colina abajo",
        "un gnomo hizo un hechizo de invisibilidad justo a tiempo",
        "la poción burbujeó y lo dejó todo pegajoso",
        "el unicornio apareció de la nada y lo empujó hacia el foso",
        "una rana gigante se sentó en su cabeza"
    ]
};